### PR TITLE
interview css task

### PR DESCRIPTION
**Pull request by SaadMahi**
Self made interview task with help of Osama Sir

### CODE REVIEW

**Review by OSAMA478 — COMMENTED** [review]
Group the selectors and style them when the elements have same stylings....

**Review by SaadMahi — COMMENTED** [review]
all similar styles grouped.

**Comment by SaadMahi** [comment]
all styles grouped please review

**Comment by SaadMahi** [comment]
grouped

**Review by murtazshaikh — APPROVED** [review]
Approved

**Comment by SaadMahi** [comment]
Good To Merge

**Pull request merged**
